version: '2.4'
services:
  nsciotservice:
    networks:
      nsciot-network:
        ipv4_address: 172.21.0.10
    image: 'nsiontech/nsciotservice:arm64-latest'
    command: ''
    env_file:
        - ./iotconfig/nscIoTConf.env
    entrypoint: /deployments/run-java.sh
    restart: unless-stopped
    working_dir: ''
    user: ''
    logging:
      driver: json-file
      options: {}
    ports:
      - '8090:8090'
    volumes:
      -   type: bind
          source: ./iotconfig/legacy
          target: /deployments/legacy
      -   type: bind
          source: ./iotconfig/statedb
          target: /deployments/statedb
      -   type: bind
          source: ./iotconfig/imagedb
          target: /deployments/imagedb
networks:
    nsciot-network:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.21.0.0/24
