    nsciot${contid}:
      restart: unless-stopped
      environment:
        - SYSTEM_UUID_KEY=${uuid}
      container_name: nsciotservice${contid}
      image: nsiontech/nsciotservice:${hw}
      volumes:
        - ./nscIotConfig/iotservice.properties${contid}:/opt/tomcat/iotservice.properties
        - ./iotkey/${iotkey}:/opt/tomcat/webapps/${iotkey}
        - ./logs/nsciotservice${contid}:/opt/tomcat/logs
      networks:
        nsciot-network:
         ipv4_address: ${ipnumber}
      ports:
        - 809${contid}:8080
      # Example for device video sources, like usb cam
      #devices:
      #  - "/dev/video0:/dev/video0"   
