version: "3.5"
services:    
    nsciot:
      restart: unless-stopped
      environment:
        - SYSTEM_UUID_KEY=${uuid}
      container_name: nsciotservice
      image: nsiontech/nsciotservice:${hw}
      volumes:
        - ./nscIotConfig/iotservice.yaml:/opt/tomcat/iotservice.yaml
        - ./iotkey/${iotkey}:/opt/tomcat/webapps/${iotkey}
        - ./logs:/opt/tomcat/logs
      networks:
        nsciot-network:
         ipv4_address: 172.21.0.10
      ports:
        - 8090:8080
      # Example for device video sources, like usb cam
      #devices:
      #  - "/dev/video0:/dev/video0"    
networks:
    nsciot-network:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.21.0.0/24
